/**
 *  * NOIZYLAB · ConsentOracle
  * ─────────────────────────────────────────────────────────────────────────────
   * Validates every voice synthesis request against the HVS consent kernel.
    * No synthesis fires without passing all 9 Never Clauses + 9 covenant checks.
     *
      * Heaven endpoint: https://heaven.rsp-5f3.workers.dev (→ heaven.noizy.ai)
       * Doctrine: Consent as executable code. Revocation as sacred.
        * killSwitchHolder: RSP_001 | covenant: 75/25 | canon: noizy.ai
         * ─────────────────────────────────────────────────────────────────────────────
          */

          import { env } from "node:process";

          // ═══════════════════════════════════════════════════════════════
          // NEVER CLAUSES — immovable law (RSP_001, 9 total)
          // ═══════════════════════════════════════════════════════════════

          export const NEVER_CLAUSES = [
            { code: "NC_POLITICAL",         category: "personal", desc: "No political campaigns" },
              { code: "NC_SEXUAL",            category: "personal", desc: "No adult content" },
                { code: "NC_WEAPONS",           category: "personal", desc: "No weapons/violence promotion" },
                  { code: "NC_DECEPTION",         category: "personal", desc: "No fraud or impersonation" },
                    { code: "NC_HATE",              category: "personal", desc: "No hate speech" },
                      { code: "NC_TRANSFER",          category: "personal", desc: "No unauthorized transfer" },
                        { code: "NC_SURVEILLANCE",      category: "personal", desc: "No surveillance or biometric ID" },
                          { code: "NC_SYSTEM_INTEGRITY",  category: "system",   desc: "Synthesis requires valid consent token" },
                            { code: "NC_SYSTEM_TRANSFER",   category: "system",   desc: "Voice DNA non-transferable outside kernel" },
                            ] as const;

                            export type NeverClauseCode = (typeof NEVER_CLAUSES)[number]["code"];

                            // ═══════════════════════════════════════════════════════════════
                            // TYPES
                            // ═══════════════════════════════════════════════════════════════

                            export interface ConsentToken {
                              id: string;
                                actorId: string;
                                  descendantId: string;
                                    purpose: string;
                                      territory: string;
                                        expiresAt: string;
                                          useCategory: string;
                                            isRevoked: boolean;
                                            }

                                            export interface CovenantCheckResult {
                                              pass: boolean;
                                                checks: {
                                                    name: string;
                                                        pass: boolean;
                                                            reason?: string;
                                                              }[];
                                                                neverClausesViolated: NeverClauseCode[];
                                                                  ledgerEventId?: string;
                                                                  }

                                                                  export interface SynthesisRequest {
                                                                    tokenId: string;
                                                                      actorId: string;
                                                                        descendantId: string;
                                                                          useCategory: string;
                                                                            territory: string;
                                                                              text: string;
                                                                                requestedAt?: string;
                                                                                }

                                                                                // ═══════════════════════════════════════════════════════════════
                                                                                // CONSENT ORACLE
                                                                                // ═══════════════════════════════════════════════════════════════

                                                                                export class ConsentOracle {
                                                                                  private readonly heavenUrl: string;
                                                                                    private readonly noizyApiKey: string;

                                                                                      constructor() {
                                                                                          this.heavenUrl = env.HEAVEN_URL || "https://heaven.rsp-5f3.workers.dev";
                                                                                              this.noizyApiKey = env.NOIZY_API_KEY || "";
                                                                                                }

                                                                                                  /**
                                                                                                     * Run the full 9-check covenant validation before any synthesis.
                                                                                                        * Returns PASS or FAIL with full audit trail.
                                                                                                           * On FAIL: logs to ledger (append-only), returns 403-equivalent.
                                                                                                              */
                                                                                                                async validate(req: SynthesisRequest): Promise<CovenantCheckResult> {
                                                                                                                    const checks: CovenantCheckResult["checks"] = [];
                                                                                                                        const neverViolated: NeverClauseCode[] = [];

                                                                                                                            // ── Check 1: Actor exists and is active ──
                                                                                                                                const actorCheck = await this._checkActor(req.actorId);
                                                                                                                                    checks.push({ name: "actor_active", ...actorCheck });

                                                                                                                                        // ── Check 2: Descendant belongs to actor ──
                                                                                                                                            const descCheck = await this._checkDescendant(req.actorId, req.descendantId);
                                                                                                                                                checks.push({ name: "descendant_belongs", ...descCheck });

                                                                                                                                                    // ── Check 3: Consent token valid + not expired ──
                                                                                                                                                        const tokenCheck = await this._checkToken(req.tokenId);
                                                                                                                                                            checks.push({ name: "token_valid", ...tokenCheck });

                                                                                                                                                                // ── Check 4: Token covers requested use category ──
                                                                                                                                                                    const catCheck = await this._checkCategory(req.tokenId, req.useCategory);
                                                                                                                                                                        checks.push({ name: "category_match", ...catCheck });

                                                                                                                                                                            // ── Check 5: Territory check ──
                                                                                                                                                                                const terrCheck = await this._checkTerritory(req.tokenId, req.territory);
                                                                                                                                                                                    checks.push({ name: "territory_pass", ...terrCheck });

                                                                                                                                                                                        // ── Checks 6: All 9 Never Clauses ──
                                                                                                                                                                                            const ncResult = this._checkNeverClauses(req.text, req.useCategory);
                                                                                                                                                                                                checks.push({ name: "never_clauses", pass: ncResult.violations.length === 0,
                                                                                                                                                                                                      reason: ncResult.violations.length > 0 ? ncResult.violations.join(", ") : undefined });
                                                                                                                                                                                                          neverViolated.push(...ncResult.violations as NeverClauseCode[]);

                                                                                                                                                                                                              // ── Check 7: Rate table entry exists ──
                                                                                                                                                                                                                  const rateCheck = await this._checkRateTable(req.useCategory);
                                                                                                                                                                                                                      checks.push({ name: "rate_table_exists", ...rateCheck });

                                                                                                                                                                                                                          // ── Check 8: License valid if required ──
                                                                                                                                                                                                                              const licCheck = await this._checkLicense(req.actorId, req.useCategory);
                                                                                                                                                                                                                                  checks.push({ name: "license_valid", ...licCheck });

                                                                                                                                                                                                                                      const allPass = checks.every((c) => c.pass) && neverViolated.length === 0;

                                                                                                                                                                                                                                          // ── Check 9: Append to ledger (always — pass or fail) ──
                                                                                                                                                                                                                                              const ledgerEventId = await this._appendLedger({
                                                                                                                                                                                                                                                    ...req,
                                                                                                                                                                                                                                                          result: allPass ? "PASS" : "FAIL",
                                                                                                                                                                                                                                                                checksRun: checks.length,
                                                                                                                                                                                                                                                                      neverClausesViolated: neverViolated,
                                                                                                                                                                                                                                                                            timestamp: new Date().toISOString(),
                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                    checks.push({ name: "ledger_appended", pass: !!ledgerEventId });

                                                                                                                                                                                                                                                                                        return { pass: allPass, checks, neverClausesViolated: neverViolated, ledgerEventId };
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                               * Revoke a consent token instantly (Kill Switch).
                                                                                                                                                                                                                                                                                                  * RSP_001 can revoke any token at any time.
                                                                                                                                                                                                                                                                                                     * Revocation is permanent — no undo.
                                                                                                                                                                                                                                                                                                        */
                                                                                                                                                                                                                                                                                                          async revoke(tokenId: string, reason: string): Promise<boolean> {
                                                                                                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                                                                                                    const res = await this._heaven(`POST`, `/api/v1/consent-tokens/${tokenId}/revoke`, { reason });
                                                                                                                                                                                                                                                                                                                          return res.success === true;
                                                                                                                                                                                                                                                                                                                              } catch {
                                                                                                                                                                                                                                                                                                                                    return false;
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                               * Verify exactly 9 Never Clauses are active in the kernel.
                                                                                                                                                                                                                                                                                                                                                  * Must return true before any deploy touching consent logic.
                                                                                                                                                                                                                                                                                                                                                     */
                                                                                                                                                                                                                                                                                                                                                       async verifyNeverClauseCount(): Promise<boolean> {
                                                                                                                                                                                                                                                                                                                                                           try {
                                                                                                                                                                                                                                                                                                                                                                 const res = await this._heaven("GET", "/api/v1/never-clauses");
                                                                                                                                                                                                                                                                                                                                                                       return Array.isArray(res.data) && res.data.filter((c: { is_active: boolean }) => c.is_active).length === 9;
                                                                                                                                                                                                                                                                                                                                                                           } catch {
                                                                                                                                                                                                                                                                                                                                                                                 return false;
                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                         // ─── private checks ─────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                           private async _checkActor(actorId: string): Promise<{ pass: boolean; reason?: string }> {
                                                                                                                                                                                                                                                                                                                                                                                               try {
                                                                                                                                                                                                                                                                                                                                                                                                     const res = await this._heaven("GET", `/api/v1/actors/${actorId}`);
                                                                                                                                                                                                                                                                                                                                                                                                           return res.data?.is_active ? { pass: true } : { pass: false, reason: "actor_inactive" };
                                                                                                                                                                                                                                                                                                                                                                                                               } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                     return { pass: false, reason: `actor_check_failed: ${(e as Error).message}` };
                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                             private async _checkDescendant(actorId: string, descendantId: string): Promise<{ pass: boolean; reason?: string }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                 try {
                                                                                                                                                                                                                                                                                                                                                                                                                                       const res = await this._heaven("GET", `/api/v1/actors/${actorId}/descendants/${descendantId}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                             return res.data ? { pass: true } : { pass: false, reason: "descendant_not_found" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                 } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                       return { pass: false, reason: `descendant_check_failed: ${(e as Error).message}` };
                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                               private async _checkToken(tokenId: string): Promise<{ pass: boolean; reason?: string }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const res = await this._heaven("GET", `/api/v1/consent-tokens/${tokenId}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const token = res.data as ConsentToken | undefined;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!token) return { pass: false, reason: "token_not_found" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (token.isRevoked) return { pass: false, reason: "token_revoked" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 if (new Date(token.expiresAt) < new Date()) return { pass: false, reason: "token_expired" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return { pass: true };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return { pass: false, reason: `token_check_failed: ${(e as Error).message}` };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         private async _checkCategory(tokenId: string, useCategory: string): Promise<{ pass: boolean; reason?: string }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const res = await this._heaven("GET", `/api/v1/consent-tokens/${tokenId}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const token = res.data as ConsentToken | undefined;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (!token) return { pass: false, reason: "token_not_found" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return token.useCategory === useCategory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ? { pass: true }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     : { pass: false, reason: `category_mismatch: expected ${token.useCategory}, got ${useCategory}` };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return { pass: false, reason: `category_check_failed: ${(e as Error).message}` };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       private async _checkTerritory(tokenId: string, territory: string): Promise<{ pass: boolean; reason?: string }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const res = await this._heaven("GET", `/api/v1/consent-tokens/${tokenId}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const token = res.data as ConsentToken | undefined;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (!token) return { pass: false, reason: "token_not_found" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const allowed = token.territory === "*" || token.territory.split(",").map((t) => t.trim()).includes(territory);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         return allowed ? { pass: true } : { pass: false, reason: `territory_blocked: ${territory}` };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return { pass: false, reason: `territory_check_failed: ${(e as Error).message}` };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           private _checkNeverClauses(text: string, useCategory: string): { violations: string[] } {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const violations: string[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const lower = text.toLowerCase();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (/\b(campaign|ballot|elect|vote for|political party)\b/i.test(lower)) violations.push("NC_POLITICAL");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (/\b(adult content|explicit|nsfw|xxx|pornograph)\b/i.test(lower)) violations.push("NC_SEXUAL");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (/\b(weapon|firearm|bomb|explosive|assassin)\b/i.test(lower)) violations.push("NC_WEAPONS");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (/\b(impersonat|fraud|scam|deceiv|fake identity)\b/i.test(lower)) violations.push("NC_DECEPTION");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (/\b(hate speech|racial slur|genocide|exterminate)\b/i.test(lower)) violations.push("NC_HATE");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (/transfer.*voice.*dna|export.*voice.*model/i.test(lower)) violations.push("NC_TRANSFER");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (/\b(surveil|biometric|facial recogni|track individual)\b/i.test(lower)) violations.push("NC_SURVEILLANCE");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return { violations };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       private async _checkRateTable(useCategory: string): Promise<{ pass: boolean; reason?: string }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 const res = await this._heaven("GET", `/api/v1/rate-table/${useCategory}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return res.data ? { pass: true } : { pass: false, reason: `no_rate_for_category: ${useCategory}` };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return { pass: false, reason: `rate_check_failed: ${(e as Error).message}` };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         private async _checkLicense(actorId: string, useCategory: string): Promise<{ pass: boolean; reason?: string }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const res = await this._heaven("GET", `/api/v1/actors/${actorId}/licenses?category=${useCategory}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         // License may not be required for all categories — pass if none needed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (!res.data || res.data.length === 0) return { pass: true };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const active = res.data.some((l: { is_active: boolean }) => l.is_active);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return active ? { pass: true } : { pass: false, reason: "license_inactive" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               } catch (e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return { pass: false, reason: `license_check_failed: ${(e as Error).message}` };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             private async _appendLedger(entry: Record<string, unknown>): Promise<string | undefined> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const res = await this._heaven("POST", "/api/v1/ledger", entry);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             return res.data?.id as string | undefined;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // Ledger failure is critical — log but don't crash
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             console.error("[ConsentOracle] LEDGER APPEND FAILED — this is serious");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return undefined;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           private async _heaven(method: string, path: string, body?: unknown): Promise<Record<string, unknown>> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const headers: Record<string, string> = { "Content-Type": "application/json" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (this.noizyApiKey) headers["Authorization"] = `Bearer ${this.noizyApiKey}`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const res = await fetch(`${this.heavenUrl}${path}`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             method,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   headers,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         body: body ? JSON.stringify(body) : undefined,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               signal: AbortSignal.timeout(5000),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (!res.ok) throw new Error(`Heaven ${method} ${path} → ${res.status}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return res.json() as Promise<Record<string, unknown>>;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             export const consentOracle = new ConsentOracle();
 */