/**
 *  * NOIZYLAB · VoiceEngine
  * ─────────────────────────────────────────────────────────────────────────────
   * Sovereign voice infrastructure for the NOIZY Empire.
    * Consumes: voice-bridge MCP (:8080), NOIZY voice-service (:9799)
     * Produces: spoken responses through Jamie Premium en-GB on GOD.local
      *
       * Doctrine: Consent as executable code. Voice DNA is non-transferable.
        * killSwitchHolder: RSP_001 | covenant: 75/25 | canon: noizy.ai
         * ─────────────────────────────────────────────────────────────────────────────
          */

          import { EventEmitter } from "node:events";
          import { env } from "node:process";

          // ═══════════════════════════════════════════════════════════════
          // TYPES
          // ═══════════════════════════════════════════════════════════════

          export type VoicePersona =
            | "gabriel"   // Jamie Premium en-GB — lead orchestrator
              | "lucy"      // Serena Premium en-AU — memory keeper
                | "pops"      // Fred — elder wisdom
                  | "shirley"   // Samantha — code precision
                    | "dream"     // Karen — vision, 5th Epoch
                      | "engr_keith" // Tom — architecture, infrastructure
                        | "cb01";     // Daniel — DNS, Cloudflare ops

                        export interface VoiceRequest {
                          text: string;
                            persona?: VoicePersona;
                              sampleRate?: number;   // default: 48000
                                bitDepth?: number;     // default: 32
                                  frequencyHz?: number;  // default: 396 (liberation frequency — RSP_001 standard)
                                    priority?: "normal" | "urgent" | "background";
                                    }

                                    export interface VoiceResponse {
                                      success: boolean;
                                        persona: VoicePersona;
                                          durationMs: number;
                                            sampleRate: number;
                                              error?: string;
                                              }

                                              export interface VoiceEngineConfig {
                                                host: string;
                                                  port: number;
                                                    apiKey: string;
                                                      defaultPersona: VoicePersona;
                                                        maxTextLength: number;
                                                          enabled: boolean;
                                                            debug: boolean;
                                                            }

                                                            // ═══════════════════════════════════════════════════════════════
                                                            // VOICE ENGINE
                                                            // ═══════════════════════════════════════════════════════════════

                                                            export class VoiceEngine extends EventEmitter {
                                                              private readonly config: VoiceEngineConfig;
                                                                private readonly baseUrl: string;
                                                                  private queue: VoiceRequest[] = [];
                                                                    private speaking = false;

                                                                      constructor(config?: Partial<VoiceEngineConfig>) {
                                                                          super();
                                                                              this.config = {
                                                                                    host: env.NOIZY_VOICE_HOST || "127.0.0.1",
                                                                                          port: Number(env.NOIZY_VOICE_PORT || 9799),
                                                                                                apiKey: env.NOIZY_API_KEY || "",
                                                                                                      defaultPersona: "gabriel",
                                                                                                            maxTextLength: 3500,
                                                                                                                  enabled: env.GABRIEL_VOICE !== "off",
                                                                                                                        debug: env.GABRIEL_VOICE_DEBUG === "true",
                                                                                                                              ...config,
                                                                                                                                  };
                                                                                                                                      this.baseUrl = `http://${this.config.host}:${this.config.port}`;
                                                                                                                                        }

                                                                                                                                          /**
                                                                                                                                             * Speak text aloud. Fire-and-forget.
                                                                                                                                                * Voice is a nice-to-have — never blocks agent execution.
                                                                                                                                                   */
                                                                                                                                                     async speak(req: VoiceRequest): Promise<VoiceResponse> {
                                                                                                                                                         const started = Date.now();
                                                                                                                                                             const persona = req.persona ?? this.config.defaultPersona;

                                                                                                                                                                 if (!this.config.enabled || !req.text) {
                                                                                                                                                                       return { success: false, persona, durationMs: 0, sampleRate: 0 };
                                                                                                                                                                           }

                                                                                                                                                                               const payload = this.prepare(req.text);
                                                                                                                                                                                   const headers: Record<string, string> = {
                                                                                                                                                                                         "Content-Type": "application/json",
                                                                                                                                                                                             };
                                                                                                                                                                                                 if (this.config.apiKey) {
                                                                                                                                                                                                       headers["Authorization"] = `Bearer ${this.config.apiKey}`;
                                                                                                                                                                                                           }

                                                                                                                                                                                                               try {
                                                                                                                                                                                                                     const res = await fetch(`${this.baseUrl}/speak`, {
                                                                                                                                                                                                                             method: "POST",
                                                                                                                                                                                                                                     headers,
                                                                                                                                                                                                                                             body: JSON.stringify({
                                                                                                                                                                                                                                                       agent: persona,
                                                                                                                                                                                                                                                                 text: payload,
                                                                                                                                                                                                                                                                           sample_rate: req.sampleRate ?? 48000,
                                                                                                                                                                                                                                                                                     bit_depth: req.bitDepth ?? 32,
                                                                                                                                                                                                                                                                                               frequency_hz: req.frequencyHz ?? 396,
                                                                                                                                                                                                                                                                                                         priority: req.priority ?? "normal",
                                                                                                                                                                                                                                                                                                                 }),
                                                                                                                                                                                                                                                                                                                         signal: AbortSignal.timeout(5000),
                                                                                                                                                                                                                                                                                                                               });

                                                                                                                                                                                                                                                                                                                                     const durationMs = Date.now() - started;

                                                                                                                                                                                                                                                                                                                                           if (!res.ok) {
                                                                                                                                                                                                                                                                                                                                                   const err = `voice-service ${res.status}: ${await res.text()}`;
                                                                                                                                                                                                                                                                                                                                                           this.emit("error", new Error(err));
                                                                                                                                                                                                                                                                                                                                                                   this._debug(`speak failed: ${err}`);
                                                                                                                                                                                                                                                                                                                                                                           return { success: false, persona, durationMs, sampleRate: 0, error: err };
                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                       const data = await res.json() as { sample_rate?: number };
                                                                                                                                                                                                                                                                                                                                                                                             this.emit("spoken", { persona, text: payload.slice(0, 80) });
                                                                                                                                                                                                                                                                                                                                                                                                   return {
                                                                                                                                                                                                                                                                                                                                                                                                           success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                   persona,
                                                                                                                                                                                                                                                                                                                                                                                                                           durationMs,
                                                                                                                                                                                                                                                                                                                                                                                                                                   sampleRate: data.sample_rate ?? 48000,
                                                                                                                                                                                                                                                                                                                                                                                                                                         };
                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                   const msg = (err as Error).message;
                                                                                                                                                                                                                                                                                                                                                                                                                                                         this._debug(`speak error: ${msg}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                               this.emit("error", new Error(msg));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     persona,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             durationMs: Date.now() - started,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     sampleRate: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             error: msg,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * Queue a voice request. Processes sequentially — prevents audio overlap.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   async queue_speak(req: VoiceRequest): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       this.queue.push(req);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (!this.speaking) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 await this._drain();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * Health check against the voice service.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 async health(): Promise<"LIVE" | "DEGRADED" | "UNREACHABLE"> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const res = await fetch(`${this.baseUrl}/health`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   signal: AbortSignal.timeout(3000),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const data = await res.json() as { status?: string };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return data.status === "ok" ? "LIVE" : "DEGRADED";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         } catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return "UNREACHABLE";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Strip markdown so TTS doesn't read raw syntax aloud.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               prepare(text: string): string {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   const stripped = text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         .replace(/```[\s\S]*?```/g, " [code block] ")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               .replace(/`([^`]+)`/g, "$1")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     .replace(/\*\*([^*]+)\*\*/g, "$1")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           .replace(/\*([^*]+)\*/g, "$1")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 .replace(/^#+\s+/gm, "")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             .replace(/_{2,}/g, "")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   .trim();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return stripped.length > this.config.maxTextLength
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ? stripped.slice(0, this.config.maxTextLength) + "..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   : stripped;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Persona registry — maps agent names to voice characteristics.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               static personaMap(): Record<VoicePersona, { voice: string; lang: string; freq: number }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         gabriel:    { voice: "Jamie",   lang: "en-GB", freq: 396 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               lucy:       { voice: "Serena",  lang: "en-AU", freq: 528 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     pops:       { voice: "Fred",    lang: "en-US", freq: 432 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           shirley:    { voice: "Samantha",lang: "en-US", freq: 396 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 dream:      { voice: "Karen",   lang: "en-AU", freq: 639 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       engr_keith: { voice: "Tom",     lang: "en-US", freq: 396 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cb01:       { voice: "Daniel",  lang: "en-GB", freq: 396 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // ─── private ────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       private async _drain(): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           this.speaking = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               while (this.queue.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     const req = this.queue.shift()!;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           await this.speak(req);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   this.speaking = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       private _debug(msg: string): void {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (this.config.debug) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 console.error(`[VoiceEngine] ${msg}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // ═══════════════════════════════════════════════════════════════
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // SINGLETON — shared across all empire modules
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // ═══════════════════════════════════════════════════════════════

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       export const voiceEngine = new VoiceEngine();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       export default voiceEngine;
 */