/**
 *  * NOIZYLAB · DazeflowLogger
  * ─────────────────────────────────────────────────────────────────────────────
   * DAZEFLOW — the empire's mission activity stream.
    * Every significant GABRIEL action gets logged here via Lucy.
     * Append-only. Never UPDATE. Never DELETE.
      *
       * Lucy routes:    dazeflow entries → long-term memory archive
        * Gabriel logs:   every mission step, consent event, kill switch activation
         * RSP_001 reads:  daily brief via gabriel.morning.md
          *
           * killSwitchHolder: RSP_001 | covenant: 75/25 | canon: noizy.ai
            * ─────────────────────────────────────────────────────────────────────────────
             */

             import { env } from "node:process";
             import { randomBytes } from "node:crypto";
             import type { EmpireBrand } from "../router/EmpireRouter.js";

             // ═══════════════════════════════════════════════════════════════
             // TYPES
             // ═══════════════════════════════════════════════════════════════

             export type DazeflowEventType =
               | "mission_start"
                 | "mission_complete"
                   | "mission_fail"
                     | "voice_spoken"
                       | "consent_pass"
                         | "consent_fail"
                           | "never_clause_hit"
                             | "kill_switch"
                               | "agent_dispatched"
                                 | "agent_complete"
                                   | "schema_promoted"
                                     | "deploy_start"
                                       | "deploy_complete"
                                         | "deploy_fail"
                                           | "ledger_append"
                                             | "morning_brief"
                                               | "health_check"
                                                 | "empire_status";

                                                 export interface DazeflowEvent {
                                                   id: string;
                                                     type: DazeflowEventType;
                                                       brand?: EmpireBrand;
                                                         agent?: string;
                                                           summary: string;
                                                             detail?: Record<string, unknown>;
                                                               timestamp: string;
                                                                 sessionId?: string;
                                                                   rspPrincipal: "RSP_001";
                                                                   }

                                                                   export interface DazeflowConfig {
                                                                     lucyUrl: string;
                                                                       apiKey: string;
                                                                         sessionId: string;
                                                                           enabled: boolean;
                                                                             debug: boolean;
                                                                             }

                                                                             // ═══════════════════════════════════════════════════════════════
                                                                             // DAZEFLOW LOGGER
                                                                             // ═══════════════════════════════════════════════════════════════

                                                                             export class DazeflowLogger {
                                                                               private readonly config: DazeflowConfig;
                                                                                 private buffer: DazeflowEvent[] = [];
                                                                                   private flushing = false;

                                                                                     constructor(config?: Partial<DazeflowConfig>) {
                                                                                         this.config = {
                                                                                               lucyUrl: env.LUCY_URL || "http://127.0.0.1:9778",
                                                                                                     apiKey: env.NOIZY_API_KEY || "",
                                                                                                           sessionId: env.GABRIEL_SESSION_ID || this._genSessionId(),
                                                                                                                 enabled: env.DAZEFLOW_ENABLED !== "false",
                                                                                                                       debug: env.GABRIEL_VOICE_DEBUG === "true",
                                                                                                                             ...config,
                                                                                                                                 };
                                                                                                                                   }

                                                                                                                                     /**
                                                                                                                                        * Log a DAZEFLOW event. Fire-and-forget, never throws.
                                                                                                                                           */
                                                                                                                                             async log(
                                                                                                                                                 type: DazeflowEventType,
                                                                                                                                                     summary: string,
                                                                                                                                                         opts?: {
                                                                                                                                                               brand?: EmpireBrand;
                                                                                                                                                                     agent?: string;
                                                                                                                                                                           detail?: Record<string, unknown>;
                                                                                                                                                                               }
                                                                                                                                                                                 ): Promise<void> {
                                                                                                                                                                                     const event: DazeflowEvent = {
                                                                                                                                                                                           id: this._genId(),
                                                                                                                                                                                                 type,
                                                                                                                                                                                                       brand: opts?.brand,
                                                                                                                                                                                                             agent: opts?.agent,
                                                                                                                                                                                                                   summary,
                                                                                                                                                                                                                         detail: opts?.detail,
                                                                                                                                                                                                                               timestamp: new Date().toISOString(),
                                                                                                                                                                                                                                     sessionId: this.config.sessionId,
                                                                                                                                                                                                                                           rspPrincipal: "RSP_001",
                                                                                                                                                                                                                                               };

                                                                                                                                                                                                                                                   this.buffer.push(event);
                                                                                                                                                                                                                                                       this._debug(`[DAZEFLOW] ${type}: ${summary}`);

                                                                                                                                                                                                                                                           if (!this.flushing) {
                                                                                                                                                                                                                                                                 void this._flush();
                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                         /**
                                                                                                                                                                                                                                                                            * Log mission start with brand context.
                                                                                                                                                                                                                                                                               */
                                                                                                                                                                                                                                                                                 missionStart(summary: string, brand?: EmpireBrand, agent?: string): Promise<void> {
                                                                                                                                                                                                                                                                                     return this.log("mission_start", summary, { brand, agent });
                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                         /**
                                                                                                                                                                                                                                                                                            * Log mission completion.
                                                                                                                                                                                                                                                                                               */
                                                                                                                                                                                                                                                                                                 missionComplete(summary: string, brand?: EmpireBrand, detail?: Record<string, unknown>): Promise<void> {
                                                                                                                                                                                                                                                                                                     return this.log("mission_complete", summary, { brand, detail });
                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                         /**
                                                                                                                                                                                                                                                                                                            * Log consent validation result.
                                                                                                                                                                                                                                                                                                               */
                                                                                                                                                                                                                                                                                                                 consentLog(passed: boolean, tokenId: string, brand?: EmpireBrand): Promise<void> {
                                                                                                                                                                                                                                                                                                                     const type = passed ? "consent_pass" : "consent_fail";
                                                                                                                                                                                                                                                                                                                         return this.log(type, `Consent ${passed ? "PASS" : "FAIL"} — token ${tokenId}`, {
                                                                                                                                                                                                                                                                                                                               brand,
                                                                                                                                                                                                                                                                                                                                     detail: { tokenId, passed, timestamp: new Date().toISOString() },
                                                                                                                                                                                                                                                                                                                                         });
                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                             /**
                                                                                                                                                                                                                                                                                                                                                * Log Kill Switch activation — highest priority event.
                                                                                                                                                                                                                                                                                                                                                   */
                                                                                                                                                                                                                                                                                                                                                     killSwitch(tokenId: string, reason: string, activatedBy = "RSP_001"): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                         return this.log("kill_switch", `KILL SWITCH: token ${tokenId} revoked — ${reason}`, {
                                                                                                                                                                                                                                                                                                                                                               detail: { tokenId, reason, activatedBy, timestamp: new Date().toISOString() },
                                                                                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                                                                                                                                          * Log Never Clause hit — blocked synthesis.
                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                               neverClauseHit(clauses: string[], context: string): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                   return this.log("never_clause_hit", `NEVER CLAUSE HIT: ${clauses.join(", ")}`, {
                                                                                                                                                                                                                                                                                                                                                                                         detail: { clauses, context, timestamp: new Date().toISOString() },
                                                                                                                                                                                                                                                                                                                                                                                             });
                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                 /**
                                                                                                                                                                                                                                                                                                                                                                                                    * Log voice spoken event.
                                                                                                                                                                                                                                                                                                                                                                                                       */
                                                                                                                                                                                                                                                                                                                                                                                                         voiceSpoken(persona: string, preview: string, brand?: EmpireBrand): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                                             return this.log("voice_spoken", `${persona} spoke: "${preview.slice(0, 60)}..."`, {
                                                                                                                                                                                                                                                                                                                                                                                                                   brand,
                                                                                                                                                                                                                                                                                                                                                                                                                         agent: persona,
                                                                                                                                                                                                                                                                                                                                                                                                                               detail: { persona, preview: preview.slice(0, 200) },
                                                                                                                                                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                                                                                                                                                                                                          * Morning brief — daily empire status summary.
                                                                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                                                                               morningBrief(summary: string, stats: Record<string, unknown>): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                   return this.log("morning_brief", summary, { detail: stats });
                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                       /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                          * Drain buffered events as a batch to Lucy.
                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
                                                                                                                                                                                                                                                                                                                                                                                                                                                               async drain(): Promise<number> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (this.buffer.length === 0) return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const batch = this.buffer.splice(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return this._sendBatch(batch);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                               /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * Get current session ID.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       get sessionId(): string {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return this.config.sessionId;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // ─── private ────────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 private async _flush(): Promise<void> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     this.flushing = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         while (this.buffer.length > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const batch = this.buffer.splice(0, 10); // 10 events per flush
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     await this._sendBatch(batch);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             this.flushing = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 private async _sendBatch(events: DazeflowEvent[]): Promise<number> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!this.config.enabled || events.length === 0) return 0;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const headers: Record<string, string> = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Content-Type": "application/json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (this.config.apiKey) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             headers["Authorization"] = `Bearer ${this.config.apiKey}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const res = await fetch(`${this.config.lucyUrl}/dazeflow/batch`, {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   method: "POST",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           headers,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   body: JSON.stringify({ events, session_id: this.config.sessionId }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           signal: AbortSignal.timeout(4000),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (!res.ok) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               this._debug(`DAZEFLOW flush failed: ${res.status}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return events.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             this._debug(`DAZEFLOW flush error: ${(err as Error).message}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           private _genId(): string {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               const date = new Date().toISOString().slice(0, 10).replace(/-/g, "");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return `daze_${date}_${randomBytes(4).toString("hex")}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       private _genSessionId(): string {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           const date = new Date().toISOString().slice(0, 10).replace(/-/g, "");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return `sess_${date}_${randomBytes(4).toString("hex")}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   private _debug(msg: string): void {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (this.config.debug) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             console.error(msg);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // ═══════════════════════════════════════════════════════════════
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // SINGLETON
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // ═══════════════════════════════════════════════════════════════

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   export const dazeflow = new DazeflowLogger();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   export default dazeflow;
 */